### ISSUE TITLE
concurrent_procs - unable to change the vaule

### ISSUE THREAD

**Issue by dthpulse** [ceph/cbt#121]
Hi
changing the concurrent_procs option vaule in yaml file doesn't have any affect to the cbt. It always working with value '3'. I found this while using benchmark librbdfio.

THX

**Comment by ASBishop** [comment]
librbdfio doesn't use the concurrent_procs option. Are you seeing this behavior with another benchmark?

"concurrent_procs" does appear in librbdfio's  archive directory tree, but the value displayed is not the config option value. It's the product of procs_per_volume, volumes_per_client and the number of clients. See references to self.total_procs in librbdfio.py

**Comment by dthpulse** [comment]
right, it  works on other benchmarks.
