### ISSUE TITLE
how to parse cbt results?

### ISSUE THREAD

**Issue by dthpulse** [ceph/cbt#151]
Hi,
just finished benchmark of our Ceph cluster with CBT tool and now I'm confused how to deal with output data. I got a large directory structure with a lot of "id" directories like:

> results/00000000/id3309284191688069537/ 

where are fio log files and some files in json format.

My point is if there is any tool or simple way how to parse these output data to human readable format, that I would be also able to compare two or more CBT benchmark tests. 

Thank you

**Comment by acalhounRH** [comment]
Dthpulse, 

I have been using elasticsearch to visualize results. scripts on the below project can give you examples on how to construct an indexer. 

https://github.com/acalhounRH/automated_ceph_test 

https://github.com/acalhounRH/automated_ceph_test/blob/master/scripts/evaluatefiojson_pushes.py
https://github.com/acalhounRH/automated_ceph_test/blob/master/scripts/evaluatefiologs_pushes.py

**Comment by dthpulse** [comment]
thx works with ELK
